#!/bin/bash

BASE_D=$PWD
SRV_F="$BASE_D/srv.info"
user=admin
XLS_D=/home/admin/incoming
EXT=xls
prefix=loc


function usage {
  cat <<EOF
  Usage : $(basename $0 [-d])
  $(basename $0) transfers *.xls files from a POM server to your computer
    using rsync over ssh.
  Connection informations are stored in a flat file that must be in your
    destination computer directory and must be named srv.info
  For a srv.info example file, see below.

  Optionnal arguments : 
    -d : distant connection (from Exosec)

  srv.info example file :
EOF
  cat $HOME/bin/srv.info.sample
}



set -f
while [ $# -gt 0 ] ; do
  case "$1" in
    # standard nagios parameters
    -h|--help)        usage         ; exit 0 ;;
  esac
  shift
done
set +f

[ ! -s $SRV_F ] && { echo "Error : $SRV_F not readable or empty" ; exit 1 ; }

source $SRV_F



# compose variables depending on prefix witch is 'loc' or 'dist'
srv=${distsrv}
port=$((locport + 22000))
echo $port

cmd="ssh listen@na.exosec.local -- -p $port localhost:443%$srv"
echo "$cmd"

echo "https://localhost:$port"
#eval $(ssh listen@na.exosec.local -- -p $port localhost:443%$srv)
eval $($cmd)
#ssh -L $port:localhost:443 ${user}@${srv}

exit $?
