FROM debian:buster-slim

RUN apt-get update && apt-get install -y apache2 && apt-get clean
RUN a2enmod proxy_fcgi && a2enmod ssl &&a2enmod rewrite

# COPY ./conf/httpd/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY /mnt/docker/shares/web/conf/000-default.conf /etc/apache2/sites-available/000-default.conf
CMD /usr/sbin/apache2ctl -D FOREGROUND
